### ISSUE TITLE
Allow hosts to assume control over presenter view

### ISSUE THREAD

**Issue by Datenyan** [darkrilin/open-picturephone#3]
Currently, the host can delegate the presenting of a particular book to a user, which holds the entire game at the mercy of the person presenting. 

As such, someone attempting to troll other players could potentially hold up games indefinitely by refusing to display new pages, which could force a room to be abandonded.

Allowing hosts to re-assume control over presenting (or end the presentation of the book prematurely) would fix this potential trolling action.

**Comment by darkrilin** [comment]
Implemented in https://github.com/darkrilin/open-picturephone/commit/f4b7f23b9a2ce1ffcb07dd6bfe835829c0b4d1ce
